apiVersion: apps/v1
kind: Deployment
metadata:
 name: javawebapp-dp #deployment name
 namespace: test-ns
spec:
 replicas: 2
 strategy:
  type: RollingUpdate
 selector:
  matchLabels: #equality based selector
   app: javawebapp #using pod label as selector
 template: #pod template
  metadata: #pod metadata
    labels: #pod labels
     app: javawebapp
  spec: #pod spec
   containers:
   - name: javawebapp #container name
     image: chaitradockerhub/java-web-app:1
     ports:
     - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: javawebappsvc #service name
 namespace: test-ns #namespace name
spec:
 type: NodePort
 selector:
  app: javawebapp #pod labels as selectors
 ports:
 - port: 80 #service port
   targetPort: 8080 #container port